### ISSUE TITLE
styles missing

### ISSUE THREAD

**Issue by mathematicalmichael** [mflevine/jupyterlab_html#11]
first of all I'd like to thank you for your work on this. what an incredibly useful extension! congrats on having it merged into core! 

the docker images I've been using don't seem to be using that core release yet, so I just installed using ` jupyter labextension install @mflevine/jupyterlab_html` and am able to see the HTML files now but there are no styles whatsoever, which doesn't seem to be the intended effect from what I can tell of the screencasts I've watched. 

what may I be doing wrong? Tried this on a few `/public` folders for websites, none appear to load in the assets correctly.

**Comment by mflevine** [comment]
Hi, glad you are getting good use out of it! I believe this relates to #4. I presume that your CSS is local and not hosted.

This extension works as expected for CSS that are hosted like:
`<link rel="stylesheet" type="text/css" href='https://fonts.googleapis.com/css?family=Open+Sans'`

However, relative urls do not work as expected because the front-end doesn't have visibility of your filesystem. Jupyter does however host your files in your tree at http://localhost:port/files so you can do a workaround like this:
`<link rel="stylesheet" type="text/css" href='http://localhost:port/files/styles.css'>`

Hope this helps!

**Comment by mathematicalmichael** [comment]
oh, I couldn't tell if that was the issue.
I'm using Jupyterhub, and a proxy server to redirect traffic to hide the ports. 
I have tried `/lab/files`, `/files` and a few other addresses and I haven't been able to get them to work. The localhost:port part becomes `...com/user/name/lab?` and I've tried putting `files` in all the possible `/` locations. Any advice? Any chance of relative links becoming supported? 

thanks for your quick reply!

**Comment by mathematicalmichael** [comment]
meanwhile, I was able to "download" the html files and preview them in my browser in the next tab. The following address shows up when I do so:
`domain.com/user/michael/files/work/BET/cover/file.html` and css does work there.
but until I download the files, I'm unable to see them. Using that path in the html itself didn't seem to work. If I navigate to where the css _would_ be, I see a Jupyterhub error: (at `domain.com/user/michael/files/work/BET/cover/style.css`)

**Comment by mflevine** [comment]
Hmmm for it to work you must be **able** to navigate to the url in the browser and either see the file or have it be downloaded depending on type of file. No additional work is likely to be done on this repo since significant work had been done once it was added to core including work on security. When we were talking about moving it we discussed relative links so it may be in core but I am unsure if it is.
